#!/bin/sh

fetch() {
  case $# in
    1) curl --location --remote-name "$1" ;;
    2) curl --location "$1" --output "$2" ;;
  esac
}

mkdir -p packages
cd packages

fetch 'https://s.ankama.com/www/static.ankama.com/ankama/www/modules/assets/logo.png' ankama.png
